---
- name: Install Apache
  hosts: webservers
  become: yes
  debugger: on_failed

  tasks:

  - name: Install apache on ubuntu
    apt:
      name: apache2
      state: present
    when: ansible_os_family == 'Debian'

  - name: Install and run apache on redhat
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"

  - name: Run apache on ubuntu
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_os_family == 'Debian'

  - name: Run apache on redhat
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_os_family == "RedHat"
