---

- hosts: webservers
  become: yes

  tasks:

  -  name: Install EPEL Repo
     yum:
        name=epel-release
        state=present
     when:
        ansible_os_family == "RedHat"

  -  name: Install nginx on RedHat Family
     yum:
        name=epel-release
        state=present
        name=nginx
        state=latest
     when:
        ansible_os_family == "RedHat"
     notify:
        nginx systemd

  -  name: Install nginx on Ubuntu
     apt:
        name=nginx
        state=latest
     when:
        ansible_os_family == "Debian"
     notify:
        nginx systemd

  handlers:
  - name: nginx systemd
    systemd:
     name: nginx.service
     enabled: yes
     state: stopped
